### ISSUE TITLE
Issue on reboot with stack with "-" in stack name

### ISSUE THREAD

**Issue by ptoulouse** [dcflachs/compose_plugin#15]
I have a number of stacks. When I reboot, they all restart, except for 2 that have hyphen in the stack name.
![image](https://user-images.githubusercontent.com/51246205/200724614-a6f4a3c2-324b-456d-b4ca-c0950f35b040.png)

 Looking at the logs, nothing particular shows up, even after enabling debug logging.
```
Nov  8 21:08:58 nas01 root: Starting compose stack: plex
Nov  8 21:08:58 nas01 root: Starting compose stack: rest-server
Nov  8 21:08:58 nas01 root: Starting compose stack: scrutiny
```
Unraid: 6.11.2
Compose Manager: 2022.10.15

Using the Compose Up button will start the stack.

**Comment by dcflachs** [comment]
Should be fixed with bfb3d9cd2b0ea3ea6df447d5fefd379ca22f3809
