### ISSUE TITLE
Updating Stack Fails

### ISSUE THREAD

**Issue by wisefella** [dcflachs/compose_plugin#16]
ENV: Unraid: 6.11.5, Compose Manager Plugin: 2022.11.17 

When attempting to update a "Docker Stack", the latest images are pulled successfully, but then the following error occurs:

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount279133007/Dockerfile: no such file or directory`

I checked and indeed there are no file/directory under the /var/lib/docker/tmp. That is, /var/lib/docker/tmp is empty.

The Web GUI->Docker, shows all the containers in the stack as 'not updated' (ie: the target containers in the stack has the "apply update" link.

**Comment by dcflachs** [comment]
What does your compose file look like? Does it contain any build directives? If so are any of those relative paths? For use with this plugin build directives should have absolute paths.

Also just to note, even if they are up to date containers will not be displayed as such in the Web GUI. This plugin does not integrate with Dockerman's update status.

**Comment by wisefella** [comment]
No build directives inside the compose file (actually, all build lines are commented out. eg:  '# build .').

The issue with the containers used by the compose manager stack not showing as up-to-date is that the 'Fix Common Problems' plugin reports this as a Warning.  So, I end up getting daily notification about the "Stack" not up-to-date.  See snapshots below.   These false-positive warnings, makes it harder to keep containers up-to-date when they're part of the Stack.  Any fix or workarounds would be awesome!

![image](https://user-images.githubusercontent.com/112023900/229652617-e73b1c57-acd5-4d1e-a2e6-1d414684cc93.png)

![image](https://user-images.githubusercontent.com/112023900/229652987-36e665e1-c8a0-4ce8-924b-f1a7586c5352.png)

**Comment by dcflachs** [comment]
The only workaround I can offer at this point is to disable notifications from 'Fix Common Problems'. The issue of update status not integrating with the unRAID web ui is something i have no plans to fix at this time.

As for the error message you posted best i can tell that comes from the docker builder. The only way I can figure that would come up is if one of the services in your compose file still had a build directive. Maybe you could try removing even the commented out lines.

**Comment by wisefella** [comment]
@dcflachs Thanks.  As suggested, I've disabled the notifications for now.  Long-term, it's probably better to use a Unraid hosted VM for Compose apps instead.
