### ISSUE TITLE
Any chance of an update to v2.20 or later?

### ISSUE THREAD

**Issue by arcoast** [dcflachs/compose_plugin#18]
Thanks for producing this, it's a really convenient way to install compose replacing my manual script I used to run to install compose.

Is there any chance you could push an update to v2.20 as I'd really like to play around with the new [`include`](https://docs.docker.com/compose/multiple-compose-files/include/) parameter which requires docker compose v2.20 as a minimum.

[v2.21.0](https://github.com/docker/compose/releases/tag/v2.21.0) is the current latest release.

**Comment by dcflachs** [comment]
Closed by 1e886091e81a755e36f56299b04e9a47fd24fc49
