### ISSUE TITLE
plugin reads every compose file while it shouldn't

### ISSUE THREAD

**Issue by tuetenk0pp** [dcflachs/compose_plugin#26]
I am using the compose plugin to host a [borgmatic](https://github.com/borgmatic-collective/docker-borgmatic) container. The file structure is as follows:

```text
.env
docker-compose.yml
docker-compose.restore.yml
```

While the plugin should automatically use any `docker-compose.override.yml` oder `compose.override.yml` file, it should *not* use the `docker-compose.restore.yml` file. I had to remove the file temporarily to be able to start the container, which is a shame because it is needed in case I need to ever recover any data from my backups.

**Comment by dcflachs** [comment]
This is working as intended. The compose manager plugin is not designed to handle compose stacks that use multiple compose files, or those which include files beyond those which are accessible from the webui interface.
