### ISSUE TITLE
Trouble with stack names containing spaces

### ISSUE THREAD

**Issue by zb140** [dcflachs/compose_plugin#3]
I created a stack with a name containing a space, and ran into some trouble.  The "up" / "down" / "pull" buttons all work just fine, but the status indicator and log viewer don't, and the buttons in the gear menu aren't working quite right either.  After some debugging, the issue seems to be that the comparison [here](https://github.com/dcflachs/compose_plugin/blob/main/source/compose.manager/php/compose_manager_main.php#L32) is using `$scriptName`, which will have spaces in it.

I can think of a few potential ways to fix this problem:
- run `$scriptName` through [`sanitizeStr`](https://github.com/dcflachs/compose_plugin/blob/main/source/compose.manager/php/compose_util.php#L11) before comparing. This is probably the lowest-effort solution.
- leave the sanitizing up to `docker-compose`. Instead of using the `projects/<project name>/name` file and `sanitizeStr`, upgrade `docker-compose` to v2.3.4+ and use `docker compose config -f projects/<project name/compose.yml --format json` to see what compose thinks the project name should be (it will be the `name` field at the top level of the returned JSON object). This solution is attractive because there's no need to keep up with what `docker-compose` thinks is valid in a project name.
- I had another idea too, but while I was writing it up I decided it was terrible so I deleted it :smile:

What do you think?

**Comment by dcflachs** [comment]
Thank you for reporting this. For now i will be going with the easy fix. Version 2022.05.08 is now available.

**Comment by zb140** [comment]
Awesome! Thanks for the quick fix!
