### ISSUE TITLE
Support for profiles?

### ISSUE THREAD

**Issue by zb140** [dcflachs/compose_plugin#4]
Have you thought at all about adding support for [profiles](https://docs.docker.com/compose/profiles/)?  I'd love to have a little drop-down or something to choose a profile when running `compose up`.  I'm happy to try to put together a PR if it's a feature you might be interested in accepting.

**Comment by dcflachs** [comment]
Profiles are an interesting feature that i was not aware of. I wonder though how much utility they would provide on unRAID. My goal with this plugin is to provide just enough functionality to support unRAID users who want to use multi-container apps via compose while keeping the maintenance and plugin complexity fairly low. What would the use case for this feature be on unRAID?

**Comment by zb140** [comment]
I'm the semi-official unRAID "expert" for a project called Games on Whales (https://github.com/games-on-whales/gow) which is essentially a set of docker containers for hardware accelerated streaming of an Xorg desktop using Sunshine and Moonlight.  It's primarily focused on gaming, but it can handle pretty much any app that uses X11 for display.

Because each piece (xorg, sunshine, steam, etc) is in its own container, we're using `docker-compose` to manage starting and stopping the whole stack.  I also recently discovered the existence of profiles, and I think it would be a great way to let people choose which apps (steam, retroarch, firefox, whatever) they want to launch when starting up the stack.  I've been experimenting with it myself with a lot of success (but it's worth noting that profiles haven't yet been added to the released version).

I'm working on an integration between GoW and this plugin so that when someone installs GoW, if they also have Docker Compose Manager it will automatically create a Compose Manager Stack for them.  Profile support would be great to have because I think it will make the user experience of launching different apps easier, but it's not a deal breaker.

**Comment by dcflachs** [comment]
Basic support for this is now available.
