### ISSUE TITLE
Allow for variable stack root directory

### ISSUE THREAD

**Issue by albahrani** [dcflachs/compose_plugin#5]
I am currently migrating my docker setup to docker compose. While evaluating possibilities to manage docker compose content in Unraid I stumbled upon your project. While it is providing 99% of what I need, one thing bothers me.

Why do I have to use `/boot/config/plugins/compose.manager/projects` to store the docker compose content? - I would prefer having it somewhere under something like `/mnt/user/docker-compose` or so.

So, having a possibility to optionally define a `content_base_path` while adding a Stack would be great.
The commands and file name conventions for being able to show and edit the stack would stay the same.
On deletion a checkbox allowing to select if you completely want to delete the  `content_base_path` directory would be nice, but not required.

It could be handled like the description, with a file called  `content_base_path` holding the path to the directory of the stack docker-compose.yml.

That would allow me to combine your awesome plugin with the possibility to use a github repo storing my docker-compose data and just cloning it to the unraid pool and then continue from there.

What do you think about it?

**Comment by aronmal** [comment]
I fully agree with this. I first thought about changing `COMPOSE_ROOT`, but not being needed to have all projects in the same directory like `/mnt/user/appdata/compose` or similar, but being able to choose a path individual for every stack is a very nice idea.

**Comment by aronmal** [comment]
@dcflachs What are the [started](https://github.com/dcflachs/compose_plugin/blob/main/source/compose.manager/event/started) and [stopping_docker](https://github.com/dcflachs/compose_plugin/blob/main/source/compose.manager/event/stopping_docker) being used for? I can not see a how they are integrated and what their propose is.

**Comment by dcflachs** [comment]
They hook into unRAID's plugin architecture. They are scripts that get run on the system started and stopping_docker events respectively.

**Comment by aronmal** [comment]
I tried ... and failed. I got so far where the prompt is by googling swal (Sweetalert), but I don't get 2 [swal](https://github.com/dcflachs/compose_plugin/blob/a733e7e6901204a2940af32c065359f8fde38c66/source/compose.manager/php/compose_manager_main.php#L150)s after another to ask for a name and a path. I have not worked too much with php so far. I would love to see this implemented tough, because then I could migrate from a start script to this great plugin with my mailcow.

**Comment by albahrani** [comment]
I also tried to implement the change and got stuck at the same problem. It seams that we either would have to change to swal2, which support such cases or use a different page (creation page, update page, ...) instead of a dialog.
I searched for other plugins doing something similar, but I must admit, that it did not help me as much as I thought.
By the way,
how do you test-install your development version? - Because that was another problem I could not figure out.

**Comment by aronmal** [comment]
Inside of the [compose.manager.plg](https://github.com/dcflachs/compose_plugin/blob/main/compose.manager.plg) is the `packageURL` linked, which is getting downloaded from:
`https://github.com/dcflachs/compose_plugin/releases/download/2022.05.27/compose.manager-package-2022.05.27.txz`
into
`/boot/config/plugins/compose.manager/`
as
`compose.manager-package-2022.05.27.txz`
It will be unpacked on every on every boot.

But I directly customized files like
`/usr/local/emhttp/plugins/compose.manager/php/compose_manager_main.php`
or
`/usr/local/emhttp/plugins/compose.manager/scripts/compose.sh`

To make the changes permanent you would need to change these files inside of the `.txz` archive.

### (No garentiered information, just what I've tried and figured out)

**Comment by aronmal** [comment]
I also have created a new branch "[my-custom](https://github.com/aronmal/compose_plugin/commits/my-custom)" and edited the `github` parameter. The Githutb Actions workflow does work without any problems.

Last question @dcflachs , how do you know the md5 of the package before running the workflow and letting it compile? Also, is it "cosmetic" or will Unraid at any given point compare the checksum and not accept my custom version without correct one?

**Comment by dcflachs** [comment]
@aronmal it is not cosmetic the checksum is checked on install. 

> how do you know the md5 of the package before running the workflow and letting it compile?

You dont, the .plg file is updated in another commit after your have compiled and released the txz package.

**Comment by aronmal** [comment]
Temporarily fix from my side until the official release from @dcflachs :

[Compose Manager Package 2022.06.24](https://github.com/aronmal/compose_plugin/releases/tag/2022.06.24)

Manually install the plugin with (uninstall the old version before):
`https://raw.githubusercontent.com/aronmal/compose_plugin/my-custom/compose.manager.plg`

> Note, my version uses `/mnt/user/appdata/compose/` instead of `/boot/config/plugins/compose.manager/projects/` and utilizes the `docker-compose.yml` instead of `compose.yml`.

**Comment by dcflachs** [comment]
It is now possible to create stacks in custom directories. The default project directory for the plugin (compose root) however remains the same and will continue to contain some plugin managed files for each stack regardless of whether or not the stack is stored in an alternate location.

**Comment by albahrani** [comment]
Using compose_plugin 2022.07.28 on unraid 6.10.3, I get the following error when clicking on "Add New Stack":

```
Uncaught ReferenceError: swal2 is not defined
    addStack https://unraid.local:9443/Docker:986
    onclick https://unraid.local:9443/Docker:1
[Docker:986:3](https://unraid.local:9443/Docker)
    addStack https://unraid.local:9443/Docker:986
    onclick https://unraid.local:9443/Docker:1
```

It seems that the sed replacement commands in pkg_build.sh do not work as expected.

**Comment by aronmal** [comment]
~~Maybe in file [compose_manager_main.php](https://github.com/dcflachs/compose_plugin/commit/c3691608de2ec2de8daf4caf5d190e2996e84d70#diff-7f3f626c93f99b9f63b96e5412bd9fe6193a12fb7d7de0a9d199554b8cac5f05) line 102?~~

Nvm, it should get loaded in line 112.

**Comment by albahrani** [comment]
I think it is the `sed` commands in `pkg_build.sh`.
e.g.
`sed -i '' 's/exports.swal/exports.swal2/' ./sweetalert2.min.js` leads to `sed: can't read s/exports.swal/exports.swal2/: No such file or directory`
If I add an **-e** parameter, it seams to work `sed -i '' -e 's/exports.swal/exports.swal2/' ./sweetalert2.min.js`.
It still returns an error, but the sweetalert2.min.js content is changed according to the expression.

**Comment by albahrani** [comment]
I executed the 4 `sed `commands line 68-71 of `pkg_build.sh`, but adding the `-e` parameter like mentioned above, from cli and the `sweetalert2.min.js` file was changed accordingly.
First test shows that the "Add New Stack" dialog is now popping up.

**Comment by albahrani** [comment]
Reading the `sed` help however clearly states:
```
If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.
```
So it should should have worked as it was.

**Comment by dcflachs** [comment]
@albahrani New version built see it that works any better.
Apparently while technically correct  `sed -i '' ...` doesnt work on some linux systems while `sed -i'' ...`does. 
I am at a loss as to how i was getting it to build correctly in testing since i use a docker based built do ensure there are no differences in the build environment between testing and release.

**Comment by albahrani** [comment]
It works now.
The replacement of `swal `with `swal2 `in `sweetalert2.min.js` has been done successfully.
