### ISSUE TITLE
Ace library missing in release from 2022.05.25

### ISSUE THREAD

**Issue by Salandora** [dcflachs/compose_plugin#6]
The Ace library is missing in release from 2022.05.25.

**Comment by Salandora** [comment]
On further inspection the problem is heres:
https://github.com/dcflachs/compose_plugin/blob/c9069c8803e40a4463cef99479bf0f7b6d993700/source/pkg_build.sh#L48

it unzips "src-noconflict" instead of "src-min-noconflict"

**Comment by dcflachs** [comment]
Thanks for reporting should be fixed now with version 2022.05.27
