### ISSUE TITLE
Support for docker-compose.override.yml

### ISSUE THREAD

**Issue by aronmal** [dcflachs/compose_plugin#7]
Hey, would it be possible to add support for using a `docker-compose.override.yml`? I did some testing to better understand process of your Plugin and have created a fix for this Problem.

But questions first:
- Is there a reason why you call the files `compose.yml` and not `docker-compose.yml`?
- Is there a reason why you use the `-f $PATH` argument? If not, running the compose up and down commands directly inside of the corresponding project folder would use the `docker-compose.yml` and `docker-compose.override.yml` by [deafult](https://medium.com/it-dead-inside/making-sense-of-docker-compose-overrides-efb757460d64).

> Each docker-compose.yml file can (and should) have a corresponding docker-compose.override.yml

I need the override yaml, because I am using Mailcow which generates the `docker-compose.yml` based on the `mailcow.conf` in the project folder. But for custom changes like [disabling ipv6](https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-disable_ipv6/) and adding `container_name` attribute and `"net.unraid.docker.icon=https://..."` labels for Unraid WebGUI Icons

> Instead of editing docker-compose.yml directly, it is preferable to create an override file for it and implement your changes to the service there. Unfortunately, this right now only seems to work for services, not for network settings.

**Comment by aronmal** [comment]
@dcflachs  https://github.com/aronmal/compose_plugin/commit/62373ee48c0afd0064c4eb6b1e3623902e9cd861 approved? Works fine for me.

**Comment by dcflachs** [comment]
I will take a look later tonight. I do already have some architectural changes to the plugin in progress, including support for adding unRAID specific labels.

**Comment by aronmal** [comment]
Temporarily fix from my side until the official release from @dcflachs :

[Compose Manager Package 2022.06.24](https://github.com/aronmal/compose_plugin/releases/tag/2022.06.24)

Manually install the plugin with (uninstall the old version before):
`https://raw.githubusercontent.com/aronmal/compose_plugin/my-custom/compose.manager.plg`

> Note, my version uses `/mnt/user/appdata/compose/` instead of `/boot/config/plugins/compose.manager/projects/` and utilizes the `docker-compose.yml` instead of `compose.yml`.

**Comment by dcflachs** [comment]
It is now possible to have multiple compose files in a stack when using an alternate stack directory. It is not yet possible to edit those alternate compose files in the ui.

**Comment by dcflachs** [comment]
@aronmal So it turn out i was correct the first time. compose.yml is in fact the preferred compose file name [spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md)
